### Push a new measurement

POST {{host}}/api/influx/write
Content-Type: application/json
Accept: application/json

{
  "measurement": "temperature",
  "field": "reading",
  "value": 17.6
}

### retrieve measure given the measurement and the given field

GET {{host}}/api/influx/query?measurement=temperature&field=reading&timespan=24
Content-Type: application/json
Accept: application/json
